### ISSUE TITLE
Add 'getting started' tutorial

### ISSUE THREAD

**Issue by prtksxna** [prtksxna/svgtranslate-prototype#3]

**Comment by prtksxna** [comment]
This was noted in the heuristic review as well. One isn't able to immediately grasp the usage of the tool.

**Comment by prtksxna** [comment]
<img width="1212" alt="screen shot 2018-09-17 at 5 40 35 am" src="https://user-images.githubusercontent.com/9491/45602455-47310880-ba3c-11e8-982e-54a49dbb0e56.png">
Thinking of a short summary of the process and a way to dismiss the section. @Niharika29, what do you think?

**Comment by Niharika29** [comment]
I like it. It's simple and clear. How about not making it dismiss-able? We have all that screen space.
How will this design look on mobile/smaller screen?

**Comment by prtksxna** [comment]
There is a cross on the top right to get rid of it. 

I haven't created mobile screens for any other pages/features, are we developing the mobile stuff too now?

**Comment by prtksxna** [comment]
Ah! The tutorial wasn't *staying* dismissed, it would come back on refresh. Fixed in e244b0c6590d9dd517a96328ccdaa97d5b8c650f.

**Comment by Niharika29** [comment]
My point was, do we need to make it dismiss-able? I would rather it stick.
